/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Validaciones;
import java.awt.Color;

/**
 *
 * @author User
 */
public class Login extends javax.swing.JPanel
{

     /**
      * Creates new form Login
      */
     public Login()
     {
          initComponents();
     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents()
     {

          jLabel3 = new javax.swing.JLabel();
          jButton1 = new javax.swing.JButton();
          jButton2 = new javax.swing.JButton();
          Login = new javax.swing.JPanel();
          jLabel1 = new javax.swing.JLabel();
          Usuario = new javax.swing.JTextField();
          Contraseña = new javax.swing.JTextField();
          Registrar = new javax.swing.JButton();
          Icono = new javax.swing.JPanel();
          UsuarioBtn = new javax.swing.JButton();
          AdministradorBtn = new javax.swing.JButton();
          Ingresar = new javax.swing.JButton();
          Ingresar1 = new javax.swing.JButton();
          jLabel4 = new javax.swing.JLabel();

          jLabel3.setText("jLabel3");

          jButton1.setText("jButton1");

          jButton2.setText("jButton2");

          Login.setBackground(new java.awt.Color(153, 153, 255));

          jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 0, 24)); // NOI18N
          jLabel1.setText("Usuario:");

          Usuario.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyTyped(java.awt.event.KeyEvent evt)
               {
                    UsuarioKeyTyped(evt);
               }
          });

          Registrar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
          Registrar.setText("Registrar");

          Icono.setBackground(new java.awt.Color(153, 153, 255));

          javax.swing.GroupLayout IconoLayout = new javax.swing.GroupLayout(Icono);
          Icono.setLayout(IconoLayout);
          IconoLayout.setHorizontalGroup(
               IconoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGap(0, 100, Short.MAX_VALUE)
          );
          IconoLayout.setVerticalGroup(
               IconoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGap(0, 100, Short.MAX_VALUE)
          );

          UsuarioBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
          UsuarioBtn.setText("Usuario");
          UsuarioBtn.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    UsuarioBtnActionPerformed(evt);
               }
          });

          AdministradorBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
          AdministradorBtn.setText("Administrador");
          AdministradorBtn.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    AdministradorBtnActionPerformed(evt);
               }
          });

          Ingresar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
          Ingresar.setText("Ingresar");

          Ingresar1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
          Ingresar1.setText("Regresar");
          Ingresar1.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    Ingresar1ActionPerformed(evt);
               }
          });

          jLabel4.setFont(new java.awt.Font("Segoe UI Variable", 0, 24)); // NOI18N
          jLabel4.setText("Contraseña: ");

          javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
          Login.setLayout(LoginLayout);
          LoginLayout.setHorizontalGroup(
               LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(LoginLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(UsuarioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(41, 41, 41)
                    .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(LoginLayout.createSequentialGroup()
                              .addComponent(Icono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                              .addComponent(AdministradorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(LoginLayout.createSequentialGroup()
                              .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap())
               .addGroup(LoginLayout.createSequentialGroup()
                    .addGap(100, 100, 100)
                    .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(Ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addGroup(LoginLayout.createSequentialGroup()
                              .addGap(40, 40, 40)
                              .addComponent(Ingresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                              .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGap(65, 65, 65))
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                              .addComponent(jLabel4)
                              .addGap(158, 158, 158))))
          );
          LoginLayout.setVerticalGroup(
               LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(LoginLayout.createSequentialGroup()
                    .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(LoginLayout.createSequentialGroup()
                              .addGap(35, 35, 35)
                              .addComponent(Icono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(LoginLayout.createSequentialGroup()
                              .addContainerGap()
                              .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(AdministradorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(UsuarioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(46, 46, 46)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(12, 12, 12)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(Ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(Ingresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(107, Short.MAX_VALUE))
          );

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
          this.setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          );
     }// </editor-fold>//GEN-END:initComponents

     private void UsuarioKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_UsuarioKeyTyped
     {//GEN-HEADEREND:event_UsuarioKeyTyped
        // Validaciones.validaEntero(evt, 4, Usuario.getText());
           Validaciones.validaAlfabeticos(evt, 10, Usuario.getText());

     }//GEN-LAST:event_UsuarioKeyTyped

     private void AdministradorBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_AdministradorBtnActionPerformed
     {//GEN-HEADEREND:event_AdministradorBtnActionPerformed
     CtrlInterfaz.cambiaColorFondo(AdministradorBtn, Color.red);
     }//GEN-LAST:event_AdministradorBtnActionPerformed

     private void UsuarioBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_UsuarioBtnActionPerformed
     {//GEN-HEADEREND:event_UsuarioBtnActionPerformed
          CtrlInterfaz.cambiaColorFondo(UsuarioBtn, Color.BLUE);
     }//GEN-LAST:event_UsuarioBtnActionPerformed

     private void Ingresar1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Ingresar1ActionPerformed
     {//GEN-HEADEREND:event_Ingresar1ActionPerformed
         
     }//GEN-LAST:event_Ingresar1ActionPerformed


     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton AdministradorBtn;
     private javax.swing.JTextField Contraseña;
     private javax.swing.JPanel Icono;
     private javax.swing.JButton Ingresar;
     private javax.swing.JButton Ingresar1;
     private javax.swing.JPanel Login;
     private javax.swing.JButton Registrar;
     private javax.swing.JTextField Usuario;
     private javax.swing.JButton UsuarioBtn;
     private javax.swing.JButton jButton1;
     private javax.swing.JButton jButton2;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     // End of variables declaration//GEN-END:variables
}
