/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

/**
 *
 * @author User
 */
public class Principal extends javax.swing.JFrame
{

     /**
      * Creates new form Principal
      */
     public Principal()
     {
          initComponents();
     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents()
     {

          Fondo = new javax.swing.JPanel();
          Opciones = new javax.swing.JPanel();
          ProductosBtn = new javax.swing.JButton();
          ClientesBtn = new javax.swing.JButton();
          VentasBtn = new javax.swing.JButton();
          ProveedoresBtn = new javax.swing.JButton();
          EmpleadosBtn = new javax.swing.JButton();
          Decoración = new javax.swing.JPanel();
          Principal = new javax.swing.JPanel();
          Productos = new javax.swing.JPanel();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

          Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

          Opciones.setBackground(new java.awt.Color(255, 255, 153));

          ProductosBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          ProductosBtn.setText("Productos");
          ProductosBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());

          ClientesBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          ClientesBtn.setText("Clientes");
          ClientesBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());

          VentasBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          VentasBtn.setText("Ventas");
          VentasBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());

          ProveedoresBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          ProveedoresBtn.setText("Proveedores");
          ProveedoresBtn.setToolTipText("");
          ProveedoresBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());

          EmpleadosBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          EmpleadosBtn.setText("Empleados");
          EmpleadosBtn.setToolTipText("");
          EmpleadosBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());

          javax.swing.GroupLayout OpcionesLayout = new javax.swing.GroupLayout(Opciones);
          Opciones.setLayout(OpcionesLayout);
          OpcionesLayout.setHorizontalGroup(
               OpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(OpcionesLayout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addGroup(OpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(ProductosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(ClientesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(VentasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(ProveedoresBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(EmpleadosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(24, Short.MAX_VALUE))
          );
          OpcionesLayout.setVerticalGroup(
               OpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(OpcionesLayout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(ProductosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(52, 52, 52)
                    .addComponent(ClientesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(52, 52, 52)
                    .addComponent(VentasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(52, 52, 52)
                    .addComponent(ProveedoresBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(52, 52, 52)
                    .addComponent(EmpleadosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(65, Short.MAX_VALUE))
          );

          Fondo.add(Opciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 500));

          Decoración.setBackground(new java.awt.Color(153, 153, 255));

          javax.swing.GroupLayout DecoraciónLayout = new javax.swing.GroupLayout(Decoración);
          Decoración.setLayout(DecoraciónLayout);
          DecoraciónLayout.setHorizontalGroup(
               DecoraciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGap(0, 190, Short.MAX_VALUE)
          );
          DecoraciónLayout.setVerticalGroup(
               DecoraciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGap(0, 500, Short.MAX_VALUE)
          );

          Fondo.add(Decoración, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 190, 500));

          Principal.setLayout(new java.awt.CardLayout());

          javax.swing.GroupLayout ProductosLayout = new javax.swing.GroupLayout(Productos);
          Productos.setLayout(ProductosLayout);
          ProductosLayout.setHorizontalGroup(
               ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGap(0, 520, Short.MAX_VALUE)
          );
          ProductosLayout.setVerticalGroup(
               ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGap(0, 500, Short.MAX_VALUE)
          );

          Principal.add(Productos, "card2");

          Fondo.add(Principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 520, 500));

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     /**
      * @param args the command line arguments
      */
     public static void main(String args[])
     {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try
          {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
               {
                    if ("Nimbus".equals(info.getName()))
                    {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex)
          {
               java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex)
          {
               java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex)
          {
               java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex)
          {
               java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable()
          {
               public void run()
               {
                    new Principal().setVisible(true);
               }
          });
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton ClientesBtn;
     private javax.swing.JPanel Decoración;
     private javax.swing.JButton EmpleadosBtn;
     private javax.swing.JPanel Fondo;
     private javax.swing.JPanel Opciones;
     private javax.swing.JPanel Principal;
     private javax.swing.JPanel Productos;
     private javax.swing.JButton ProductosBtn;
     private javax.swing.JButton ProveedoresBtn;
     private javax.swing.JButton VentasBtn;
     // End of variables declaration//GEN-END:variables
}
