package Interfaz;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Validaciones;
import javax.swing.JOptionPane;
import Gestiones.Registros;
import BD.Conexion;
import com.mysql.cj.xdevapi.Statement;

public class PrincipalAdministrador extends javax.swing.JFrame
{

     public PrincipalAdministrador()
     {
          initComponents();
     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents()
     {

          jScrollBar1 = new javax.swing.JScrollBar();
          Fondo = new javax.swing.JPanel();
          Opciones = new javax.swing.JPanel();
          ProductosBtn = new javax.swing.JButton();
          VentasBtn = new javax.swing.JButton();
          ProveedoresBtn = new javax.swing.JButton();
          EmpleadosBtn = new javax.swing.JButton();
          Tablas = new javax.swing.JPanel();
          TablaProductos = new javax.swing.JPanel();
          jScrollPane1 = new javax.swing.JScrollPane();
          TProductos = new javax.swing.JTable();
          jLabel5 = new javax.swing.JLabel();
          CargarProductos = new javax.swing.JButton();
          EProducto = new javax.swing.JButton();
          MProducto1 = new javax.swing.JButton();
          TablaClientes = new javax.swing.JPanel();
          jLabel9 = new javax.swing.JLabel();
          jScrollPane2 = new javax.swing.JScrollPane();
          TClientes = new javax.swing.JTable();
          ECliente = new javax.swing.JButton();
          MCliente = new javax.swing.JButton();
          CargarProductos1 = new javax.swing.JButton();
          TablaVentas = new javax.swing.JPanel();
          jLabel10 = new javax.swing.JLabel();
          jScrollPane3 = new javax.swing.JScrollPane();
          TClientes1 = new javax.swing.JTable();
          CargarProductos2 = new javax.swing.JButton();
          CargarProductos3 = new javax.swing.JButton();
          TablaProveedores = new javax.swing.JPanel();
          jLabel18 = new javax.swing.JLabel();
          jScrollPane5 = new javax.swing.JScrollPane();
          TProveedores = new javax.swing.JTable();
          CargarProductos4 = new javax.swing.JButton();
          TablaEmpleados = new javax.swing.JPanel();
          jLabel19 = new javax.swing.JLabel();
          jScrollPane4 = new javax.swing.JScrollPane();
          jTable1 = new javax.swing.JTable();
          CargarProductos5 = new javax.swing.JButton();
          Principal = new javax.swing.JPanel();
          Productos = new javax.swing.JPanel();
          jLabel2 = new javax.swing.JLabel();
          jLabel3 = new javax.swing.JLabel();
          jLabel4 = new javax.swing.JLabel();
          NProducto = new javax.swing.JTextField();
          PProducto = new javax.swing.JTextField();
          IDProducto = new javax.swing.JTextField();
          RProductos = new javax.swing.JButton();
          CProductos = new javax.swing.JButton();
          Ventas = new javax.swing.JPanel();
          jLabel8 = new javax.swing.JLabel();
          jComboBox1 = new javax.swing.JComboBox<>();
          Proveedores = new javax.swing.JPanel();
          jLabel11 = new javax.swing.JLabel();
          NProveedor = new javax.swing.JTextField();
          jLabel12 = new javax.swing.JLabel();
          IDProveedor = new javax.swing.JTextField();
          jLabel13 = new javax.swing.JLabel();
          jLabel14 = new javax.swing.JLabel();
          UProveedor = new javax.swing.JTextField();
          RProveedores = new javax.swing.JButton();
          CProveedores = new javax.swing.JButton();
          RProductos1 = new javax.swing.JButton();
          CProductos1 = new javax.swing.JButton();
          jLabel20 = new javax.swing.JLabel();
          TProveedor = new javax.swing.JTextField();
          Empleados = new javax.swing.JPanel();
          jLabel15 = new javax.swing.JLabel();
          jLabel16 = new javax.swing.JLabel();
          jLabel17 = new javax.swing.JLabel();
          NEmpleado = new javax.swing.JTextField();
          IDEmpleado1 = new javax.swing.JTextField();
          TEmpleado = new javax.swing.JTextField();
          CEmpleado = new javax.swing.JButton();
          REmpleado = new javax.swing.JButton();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

          Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

          Opciones.setBackground(new java.awt.Color(255, 255, 153));

          ProductosBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          ProductosBtn.setText("Productos");
          ProductosBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          ProductosBtn.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    ProductosBtnActionPerformed(evt);
               }
          });

          VentasBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          VentasBtn.setText("Ventas");
          VentasBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          VentasBtn.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    VentasBtnActionPerformed(evt);
               }
          });

          ProveedoresBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          ProveedoresBtn.setText("Proveedores");
          ProveedoresBtn.setToolTipText("");
          ProveedoresBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          ProveedoresBtn.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    ProveedoresBtnActionPerformed(evt);
               }
          });

          EmpleadosBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          EmpleadosBtn.setText("Empleados");
          EmpleadosBtn.setToolTipText("");
          EmpleadosBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          EmpleadosBtn.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    EmpleadosBtnActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout OpcionesLayout = new javax.swing.GroupLayout(Opciones);
          Opciones.setLayout(OpcionesLayout);
          OpcionesLayout.setHorizontalGroup(
               OpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(OpcionesLayout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addGroup(OpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(ProductosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(VentasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(ProveedoresBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(EmpleadosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(24, Short.MAX_VALUE))
          );
          OpcionesLayout.setVerticalGroup(
               OpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(OpcionesLayout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(ProductosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(86, 86, 86)
                    .addComponent(VentasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(74, 74, 74)
                    .addComponent(ProveedoresBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(83, 83, 83)
                    .addComponent(EmpleadosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(65, Short.MAX_VALUE))
          );

          Fondo.add(Opciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 500));

          Tablas.setBackground(new java.awt.Color(153, 153, 255));
          Tablas.setLayout(new java.awt.CardLayout());

          TablaProductos.setBackground(new java.awt.Color(204, 204, 255));

          TProductos.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][]
               {
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null}
               },
               new String []
               {
                    "ID", "Nombre", "Precio Unitario"
               }
          ));
          TProductos.addAncestorListener(new javax.swing.event.AncestorListener()
          {
               public void ancestorAdded(javax.swing.event.AncestorEvent evt)
               {
                    TProductosAncestorAdded(evt);
               }
               public void ancestorMoved(javax.swing.event.AncestorEvent evt)
               {
               }
               public void ancestorRemoved(javax.swing.event.AncestorEvent evt)
               {
               }
          });
          jScrollPane1.setViewportView(TProductos);

          jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel5.setText("Productos registrados:");

          CargarProductos.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          CargarProductos.setText("Cargar");
          CargarProductos.setToolTipText("");
          CargarProductos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          CargarProductos.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    CargarProductosActionPerformed(evt);
               }
          });

          EProducto.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          EProducto.setText("Eliminar");
          EProducto.setToolTipText("");
          EProducto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          EProducto.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    EProductoActionPerformed(evt);
               }
          });

          MProducto1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          MProducto1.setText("Modificar");
          MProducto1.setToolTipText("");
          MProducto1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          MProducto1.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    MProducto1ActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout TablaProductosLayout = new javax.swing.GroupLayout(TablaProductos);
          TablaProductos.setLayout(TablaProductosLayout);
          TablaProductosLayout.setHorizontalGroup(
               TablaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(TablaProductosLayout.createSequentialGroup()
                    .addGroup(TablaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(TablaProductosLayout.createSequentialGroup()
                              .addContainerGap()
                              .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                         .addGroup(TablaProductosLayout.createSequentialGroup()
                              .addGroup(TablaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(TablaProductosLayout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(MProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(EProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addGroup(TablaProductosLayout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                              .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap())
               .addGroup(TablaProductosLayout.createSequentialGroup()
                    .addGap(79, 79, 79)
                    .addComponent(CargarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );
          TablaProductosLayout.setVerticalGroup(
               TablaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(TablaProductosLayout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(CargarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(45, 45, 45)
                    .addGroup(TablaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(TablaProductosLayout.createSequentialGroup()
                              .addComponent(EProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(0, 0, Short.MAX_VALUE))
                         .addComponent(MProducto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap())
          );

          Tablas.add(TablaProductos, "card2");

          TablaClientes.setBackground(new java.awt.Color(204, 204, 255));

          jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel9.setText("Clientes:");

          TClientes.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][]
               {
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null}
               },
               new String []
               {
                    "ID", "Nombre", "Precio Unitario"
               }
          ));
          jScrollPane2.setViewportView(TClientes);

          ECliente.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          ECliente.setText("Eliminar");
          ECliente.setToolTipText("");
          ECliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          ECliente.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    EClienteActionPerformed(evt);
               }
          });

          MCliente.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          MCliente.setText("Modificar");
          MCliente.setToolTipText("");
          MCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          MCliente.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    MClienteActionPerformed(evt);
               }
          });

          CargarProductos1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          CargarProductos1.setText("Cargar");
          CargarProductos1.setToolTipText("");
          CargarProductos1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          CargarProductos1.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    CargarProductos1ActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout TablaClientesLayout = new javax.swing.GroupLayout(TablaClientes);
          TablaClientes.setLayout(TablaClientesLayout);
          TablaClientesLayout.setHorizontalGroup(
               TablaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(TablaClientesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(TablaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                         .addGroup(TablaClientesLayout.createSequentialGroup()
                              .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(0, 21, Short.MAX_VALUE))
                         .addGroup(TablaClientesLayout.createSequentialGroup()
                              .addComponent(MCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addComponent(ECliente, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap())
               .addGroup(TablaClientesLayout.createSequentialGroup()
                    .addGap(81, 81, 81)
                    .addComponent(CargarProductos1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );
          TablaClientesLayout.setVerticalGroup(
               TablaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(TablaClientesLayout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(42, 42, 42)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(CargarProductos1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                    .addGroup(TablaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(MCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(ECliente, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap())
          );

          Tablas.add(TablaClientes, "card3");

          TablaVentas.setBackground(new java.awt.Color(204, 204, 255));

          jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel10.setText("Productos mas vendidos:");

          TClientes1.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][]
               {
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null}
               },
               new String []
               {
                    "ID", "Nombre", "Precio Unitario"
               }
          ));
          jScrollPane3.setViewportView(TClientes1);

          CargarProductos2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          CargarProductos2.setText("Cargar");
          CargarProductos2.setToolTipText("");
          CargarProductos2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          CargarProductos2.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    CargarProductos2ActionPerformed(evt);
               }
          });

          CargarProductos3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          CargarProductos3.setText("Cargar");
          CargarProductos3.setToolTipText("");
          CargarProductos3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          CargarProductos3.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    CargarProductos3ActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout TablaVentasLayout = new javax.swing.GroupLayout(TablaVentas);
          TablaVentas.setLayout(TablaVentasLayout);
          TablaVentasLayout.setHorizontalGroup(
               TablaVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(TablaVentasLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(TablaVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(TablaVentasLayout.createSequentialGroup()
                              .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(0, 21, Short.MAX_VALUE))
                         .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addContainerGap())
               .addGroup(TablaVentasLayout.createSequentialGroup()
                    .addGap(83, 83, 83)
                    .addComponent(CargarProductos3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addGroup(TablaVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TablaVentasLayout.createSequentialGroup()
                         .addGap(85, 85, 85)
                         .addComponent(CargarProductos2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addContainerGap(85, Short.MAX_VALUE)))
          );
          TablaVentasLayout.setVerticalGroup(
               TablaVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(TablaVentasLayout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(38, 38, 38)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(CargarProductos3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(76, Short.MAX_VALUE))
               .addGroup(TablaVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TablaVentasLayout.createSequentialGroup()
                         .addGap(232, 232, 232)
                         .addComponent(CargarProductos2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addContainerGap(233, Short.MAX_VALUE)))
          );

          Tablas.add(TablaVentas, "card4");

          TablaProveedores.setBackground(new java.awt.Color(204, 204, 255));

          jLabel18.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel18.setText("Proveedores:");

          TProveedores.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][]
               {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
               },
               new String []
               {
                    "ID", "Teléfono", "Nombre", "Ubicación"
               }
          ));
          TProveedores.addAncestorListener(new javax.swing.event.AncestorListener()
          {
               public void ancestorAdded(javax.swing.event.AncestorEvent evt)
               {
                    TProveedoresAncestorAdded(evt);
               }
               public void ancestorMoved(javax.swing.event.AncestorEvent evt)
               {
               }
               public void ancestorRemoved(javax.swing.event.AncestorEvent evt)
               {
               }
          });
          jScrollPane5.setViewportView(TProveedores);

          CargarProductos4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          CargarProductos4.setText("Cargar");
          CargarProductos4.setToolTipText("");
          CargarProductos4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          CargarProductos4.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    CargarProductos4ActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout TablaProveedoresLayout = new javax.swing.GroupLayout(TablaProveedores);
          TablaProveedores.setLayout(TablaProveedoresLayout);
          TablaProveedoresLayout.setHorizontalGroup(
               TablaProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(TablaProveedoresLayout.createSequentialGroup()
                    .addGroup(TablaProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(TablaProveedoresLayout.createSequentialGroup()
                              .addGap(81, 81, 81)
                              .addComponent(CargarProductos4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(TablaProveedoresLayout.createSequentialGroup()
                              .addGap(15, 15, 15)
                              .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(18, Short.MAX_VALUE))
               .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
          );
          TablaProveedoresLayout.setVerticalGroup(
               TablaProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(TablaProveedoresLayout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(70, 70, 70)
                    .addComponent(CargarProductos4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(46, Short.MAX_VALUE))
          );

          Tablas.add(TablaProveedores, "card5");

          TablaEmpleados.setBackground(new java.awt.Color(204, 204, 255));

          jLabel19.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel19.setText("Empleados:");

          jTable1.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][]
               {
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null}
               },
               new String []
               {
                    "ID", "Nombre", "Teléfono"
               }
          ));
          jScrollPane4.setViewportView(jTable1);

          CargarProductos5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          CargarProductos5.setText("Cargar");
          CargarProductos5.setToolTipText("");
          CargarProductos5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          CargarProductos5.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    CargarProductos5ActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout TablaEmpleadosLayout = new javax.swing.GroupLayout(TablaEmpleados);
          TablaEmpleados.setLayout(TablaEmpleadosLayout);
          TablaEmpleadosLayout.setHorizontalGroup(
               TablaEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(TablaEmpleadosLayout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addGroup(TablaEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                         .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(18, Short.MAX_VALUE))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TablaEmpleadosLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CargarProductos5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(78, 78, 78))
          );
          TablaEmpleadosLayout.setVerticalGroup(
               TablaEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(TablaEmpleadosLayout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(CargarProductos5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(109, Short.MAX_VALUE))
          );

          Tablas.add(TablaEmpleados, "card6");

          Fondo.add(Tablas, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 290, 500));

          Principal.setLayout(new java.awt.CardLayout());

          jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel2.setText("Nombre del producto:");

          jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel3.setText("Precio del producto por unidad: ");

          jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel4.setText("ID del producto:");

          NProducto.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
          NProducto.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyTyped(java.awt.event.KeyEvent evt)
               {
                    NProductoKeyTyped(evt);
               }
          });

          PProducto.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
          PProducto.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyTyped(java.awt.event.KeyEvent evt)
               {
                    PProductoKeyTyped(evt);
               }
          });

          IDProducto.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
          IDProducto.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyTyped(java.awt.event.KeyEvent evt)
               {
                    IDProductoKeyTyped(evt);
               }
          });

          RProductos.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          RProductos.setText("Registrar");
          RProductos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          RProductos.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    RProductosActionPerformed(evt);
               }
          });

          CProductos.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          CProductos.setText("Cancelar");
          CProductos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          CProductos.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    CProductosActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout ProductosLayout = new javax.swing.GroupLayout(Productos);
          Productos.setLayout(ProductosLayout);
          ProductosLayout.setHorizontalGroup(
               ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(ProductosLayout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addGroup(ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(NProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel3)
                         .addComponent(PProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel4)
                         .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addGroup(ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                              .addGroup(ProductosLayout.createSequentialGroup()
                                   .addComponent(RProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                   .addComponent(CProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addComponent(IDProducto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(44, Short.MAX_VALUE))
          );
          ProductosLayout.setVerticalGroup(
               ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(ProductosLayout.createSequentialGroup()
                    .addGap(106, 106, 106)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(NProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(PProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(IDProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(RProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(CProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(35, 35, 35))
          );

          Principal.add(Productos, "card2");

          jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel8.setText("Ventas por:");

          jComboBox1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
          jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--OPCIONES--", "Ültimo mes", "Ültima semana", "Lo mas vendido\t", "Lo menos vendido", " ", " " }));

          javax.swing.GroupLayout VentasLayout = new javax.swing.GroupLayout(Ventas);
          Ventas.setLayout(VentasLayout);
          VentasLayout.setHorizontalGroup(
               VentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(VentasLayout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(31, 31, 31)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(64, Short.MAX_VALUE))
          );
          VentasLayout.setVerticalGroup(
               VentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(VentasLayout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addGroup(VentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(412, Short.MAX_VALUE))
          );

          Principal.add(Ventas, "card3");

          jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel11.setText("Ubicación del proveedor:");

          NProveedor.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
          NProveedor.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyTyped(java.awt.event.KeyEvent evt)
               {
                    NProveedorKeyTyped(evt);
               }
          });

          jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel12.setText("ID del proveedor:");

          IDProveedor.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
          IDProveedor.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyTyped(java.awt.event.KeyEvent evt)
               {
                    IDProveedorKeyTyped(evt);
               }
          });

          jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel13.setText("Nombre del proveedor:");

          jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel14.setText("Teléfono del proveedor:");

          UProveedor.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
          UProveedor.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyTyped(java.awt.event.KeyEvent evt)
               {
                    UProveedorKeyTyped(evt);
               }
          });

          RProveedores.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          RProveedores.setText("Registrar");
          RProveedores.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          RProveedores.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    RProveedoresActionPerformed(evt);
               }
          });

          CProveedores.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          CProveedores.setText("Cancelar");
          CProveedores.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          CProveedores.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    CProveedoresActionPerformed(evt);
               }
          });

          RProductos1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          RProductos1.setText("Registrar");
          RProductos1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          RProductos1.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    RProductos1ActionPerformed(evt);
               }
          });

          CProductos1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          CProductos1.setText("Cancelar");
          CProductos1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          CProductos1.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    CProductos1ActionPerformed(evt);
               }
          });

          jLabel20.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel20.setText("Telefono del proveedor: ");

          TProveedor.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
          TProveedor.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyTyped(java.awt.event.KeyEvent evt)
               {
                    TProveedorKeyTyped(evt);
               }
          });

          javax.swing.GroupLayout ProveedoresLayout = new javax.swing.GroupLayout(Proveedores);
          Proveedores.setLayout(ProveedoresLayout);
          ProveedoresLayout.setHorizontalGroup(
               ProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(ProveedoresLayout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addGroup(ProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(TProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addGroup(ProveedoresLayout.createSequentialGroup()
                              .addComponent(RProductos1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(18, 18, 18)
                              .addComponent(CProductos1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(IDProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(NProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addGroup(ProveedoresLayout.createSequentialGroup()
                              .addComponent(RProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(67, 67, 67)
                              .addComponent(CProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addComponent(UProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(41, Short.MAX_VALUE))
          );
          ProveedoresLayout.setVerticalGroup(
               ProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(ProveedoresLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(IDProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(NProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(UProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(TProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(31, 31, 31)
                    .addGroup(ProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                         .addComponent(RProductos1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                         .addComponent(CProductos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(632, 632, 632)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(75, 75, 75)
                    .addGroup(ProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(RProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(CProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );

          Principal.add(Proveedores, "card5");

          jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel15.setText("Nombre del empleado:");

          jLabel16.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel16.setText("Teléfono del empleado:");

          jLabel17.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
          jLabel17.setText("ID del empleado:");

          NEmpleado.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
          NEmpleado.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyTyped(java.awt.event.KeyEvent evt)
               {
                    NEmpleadoKeyTyped(evt);
               }
          });

          IDEmpleado1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
          IDEmpleado1.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyTyped(java.awt.event.KeyEvent evt)
               {
                    IDEmpleado1KeyTyped(evt);
               }
          });

          TEmpleado.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
          TEmpleado.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyTyped(java.awt.event.KeyEvent evt)
               {
                    TEmpleadoKeyTyped(evt);
               }
          });

          CEmpleado.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          CEmpleado.setText("Cancelar");
          CEmpleado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          CEmpleado.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    CEmpleadoActionPerformed(evt);
               }
          });

          REmpleado.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
          REmpleado.setText("Registrar");
          REmpleado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          REmpleado.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    REmpleadoActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout EmpleadosLayout = new javax.swing.GroupLayout(Empleados);
          Empleados.setLayout(EmpleadosLayout);
          EmpleadosLayout.setHorizontalGroup(
               EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(EmpleadosLayout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addGroup(EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(IDEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(NEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addGroup(EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                              .addGroup(EmpleadosLayout.createSequentialGroup()
                                   .addComponent(REmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                   .addComponent(CEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addComponent(TEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(32, Short.MAX_VALUE))
          );
          EmpleadosLayout.setVerticalGroup(
               EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(EmpleadosLayout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(IDEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(NEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(TEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(REmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(CEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(110, Short.MAX_VALUE))
          );

          Principal.add(Empleados, "card6");

          Fondo.add(Principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 420, 500));

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void NProductoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_NProductoKeyTyped
     {//GEN-HEADEREND:event_NProductoKeyTyped

          Validaciones.validaAlfabeticos(evt, 20, NProducto.getText());

     }//GEN-LAST:event_NProductoKeyTyped

     private void PProductoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_PProductoKeyTyped
     {//GEN-HEADEREND:event_PProductoKeyTyped
          Validaciones.enterEntero(this, evt, PProducto, evt);
     }//GEN-LAST:event_PProductoKeyTyped

     private void ProductosBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ProductosBtnActionPerformed
     {//GEN-HEADEREND:event_ProductosBtnActionPerformed

          Tablas.removeAll();
          Tablas.add(TablaProductos);
          Tablas.repaint();
          Tablas.revalidate();

          Principal.removeAll();
          Principal.add(Productos);
          Principal.repaint();
          Principal.revalidate();     }//GEN-LAST:event_ProductosBtnActionPerformed

     private void VentasBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_VentasBtnActionPerformed
     {//GEN-HEADEREND:event_VentasBtnActionPerformed
          Tablas.removeAll();
          Tablas.add(TablaVentas);
          Tablas.repaint();
          Tablas.revalidate();

          Principal.removeAll();
          Principal.add(Ventas);
          Principal.repaint();
          Principal.revalidate();     }//GEN-LAST:event_VentasBtnActionPerformed

     private void ProveedoresBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ProveedoresBtnActionPerformed
     {//GEN-HEADEREND:event_ProveedoresBtnActionPerformed
          Tablas.removeAll();
          Tablas.add(TablaProveedores);
          Tablas.repaint();
          Tablas.revalidate();

          Principal.removeAll();
          Principal.add(Proveedores);
          Principal.repaint();
          Principal.revalidate();     }//GEN-LAST:event_ProveedoresBtnActionPerformed

     private void EmpleadosBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_EmpleadosBtnActionPerformed
     {//GEN-HEADEREND:event_EmpleadosBtnActionPerformed
          Tablas.removeAll();
          Tablas.add(TablaEmpleados);
          Tablas.repaint();
          Tablas.revalidate();

          Principal.removeAll();
          Principal.add(Empleados);
          Principal.repaint();
          Principal.revalidate();     }//GEN-LAST:event_EmpleadosBtnActionPerformed

     private void IDProductoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_IDProductoKeyTyped
     {//GEN-HEADEREND:event_IDProductoKeyTyped
          Validaciones.validaEntero(evt, 2, IDProducto.getText());
     }//GEN-LAST:event_IDProductoKeyTyped

     private void CargarProductosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CargarProductosActionPerformed
     {//GEN-HEADEREND:event_CargarProductosActionPerformed


     }//GEN-LAST:event_CargarProductosActionPerformed

     private void EProductoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_EProductoActionPerformed
     {//GEN-HEADEREND:event_EProductoActionPerformed
          // TODO add your handling code here:
     }//GEN-LAST:event_EProductoActionPerformed


     private void RProductosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RProductosActionPerformed
     {//GEN-HEADEREND:event_RProductosActionPerformed
          String nombre = NProducto.getText().trim();
          String precioStr = PProducto.getText().trim();
          String idStr = IDProducto.getText().trim();

          if (nombre.isEmpty() || precioStr.isEmpty() || idStr.isEmpty())
          {
               JOptionPane.showMessageDialog(this,
                       "Todos los campos son obligatorios",
                       "Error",
                       JOptionPane.ERROR_MESSAGE);
               return;
          }

          try
          {
               double precio = Double.parseDouble(precioStr);
               int id = Integer.parseInt(idStr);

               Registros registros = new Registros();
               boolean insertado = registros.insertarProducto(nombre, precio, id);

               if (insertado)
               {
                    JOptionPane.showMessageDialog(this,
                            "Producto registrado exitosamente",
                            "Éxito",
                            JOptionPane.INFORMATION_MESSAGE);
                    CtrlInterfaz.limpia(NProducto);
                    CtrlInterfaz.limpia(PProducto);
                    CtrlInterfaz.limpia(IDProducto);

               } else
               {
                    JOptionPane.showMessageDialog(this,
                            "No se pudo registrar el producto",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
               }
          } catch (NumberFormatException e)
          {
               JOptionPane.showMessageDialog(this,
                       "El precio y el ID deben ser números válidos",
                       "Error",
                       JOptionPane.ERROR_MESSAGE);
          }
     }//GEN-LAST:event_RProductosActionPerformed

     private void CProductosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CProductosActionPerformed
     {//GEN-HEADEREND:event_CProductosActionPerformed
          CtrlInterfaz.limpia(NProducto);
          CtrlInterfaz.limpia(PProducto);
          CtrlInterfaz.limpia(IDProducto);     }//GEN-LAST:event_CProductosActionPerformed

     private void EClienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_EClienteActionPerformed
     {//GEN-HEADEREND:event_EClienteActionPerformed
          // TODO add your handling code here:
     }//GEN-LAST:event_EClienteActionPerformed

     private void MClienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MClienteActionPerformed
     {//GEN-HEADEREND:event_MClienteActionPerformed
          // TODO add your handling code here:
     }//GEN-LAST:event_MClienteActionPerformed

     private void NProveedorKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_NProveedorKeyTyped
     {//GEN-HEADEREND:event_NProveedorKeyTyped
          // TODO add your handling code here:
     }//GEN-LAST:event_NProveedorKeyTyped

     private void IDProveedorKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_IDProveedorKeyTyped
     {//GEN-HEADEREND:event_IDProveedorKeyTyped
          Validaciones.validaEntero(evt);
     }//GEN-LAST:event_IDProveedorKeyTyped

     private void UProveedorKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_UProveedorKeyTyped
     {//GEN-HEADEREND:event_UProveedorKeyTyped
          // TODO add your handling code here:
     }//GEN-LAST:event_UProveedorKeyTyped

     private void RProveedoresActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RProveedoresActionPerformed
     {//GEN-HEADEREND:event_RProveedoresActionPerformed


     }//GEN-LAST:event_RProveedoresActionPerformed

     private void CProveedoresActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CProveedoresActionPerformed
     {//GEN-HEADEREND:event_CProveedoresActionPerformed
          // TODO add your handling code here:
     }//GEN-LAST:event_CProveedoresActionPerformed

     private void TProveedoresAncestorAdded(javax.swing.event.AncestorEvent evt)//GEN-FIRST:event_TProveedoresAncestorAdded
     {//GEN-HEADEREND:event_TProveedoresAncestorAdded
     }//GEN-LAST:event_TProveedoresAncestorAdded


     private void TProductosAncestorAdded(javax.swing.event.AncestorEvent evt)//GEN-FIRST:event_TProductosAncestorAdded
     {//GEN-HEADEREND:event_TProductosAncestorAdded

     }//GEN-LAST:event_TProductosAncestorAdded

     private void MProducto1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MProducto1ActionPerformed
     {//GEN-HEADEREND:event_MProducto1ActionPerformed
          // TODO add your handling code here:
     }//GEN-LAST:event_MProducto1ActionPerformed

     private void CProductos1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CProductos1ActionPerformed
     {//GEN-HEADEREND:event_CProductos1ActionPerformed
          CtrlInterfaz.limpia(UProveedor);
          CtrlInterfaz.limpia(NProveedor);
          CtrlInterfaz.limpia(IDProveedor);
          CtrlInterfaz.limpia(TProveedor);

     }//GEN-LAST:event_CProductos1ActionPerformed

     private void CargarProductos1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CargarProductos1ActionPerformed
     {//GEN-HEADEREND:event_CargarProductos1ActionPerformed
          // TODO add your handling code here:
     }//GEN-LAST:event_CargarProductos1ActionPerformed

     private void CargarProductos2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CargarProductos2ActionPerformed
     {//GEN-HEADEREND:event_CargarProductos2ActionPerformed
          // TODO add your handling code here:
     }//GEN-LAST:event_CargarProductos2ActionPerformed

     private void CargarProductos3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CargarProductos3ActionPerformed
     {//GEN-HEADEREND:event_CargarProductos3ActionPerformed
          // TODO add your handling code here:
     }//GEN-LAST:event_CargarProductos3ActionPerformed

     private void CargarProductos4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CargarProductos4ActionPerformed
     {//GEN-HEADEREND:event_CargarProductos4ActionPerformed
          // TODO add your handling code here:
     }//GEN-LAST:event_CargarProductos4ActionPerformed

     private void CargarProductos5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CargarProductos5ActionPerformed
     {//GEN-HEADEREND:event_CargarProductos5ActionPerformed
          // TODO add your handling code here:
     }//GEN-LAST:event_CargarProductos5ActionPerformed

     private void RProductos1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RProductos1ActionPerformed
     {//GEN-HEADEREND:event_RProductos1ActionPerformed

          String nom = NProveedor.getText().trim();
          String ubi = UProveedor.getText().trim();
          String TelStr = TProveedor.getText().trim();
          String IdStr = IDProveedor.getText().trim();

          if (nom.isEmpty() || ubi.isEmpty() || TelStr.isEmpty() || IdStr.isEmpty())
          {
               JOptionPane.showMessageDialog(this,
                       "Todos los campos son obligatorios",
                       "Error",
                       JOptionPane.ERROR_MESSAGE);
               return;
          }
          try
          {

               int tel = Integer.parseInt(TelStr);
               int id = Integer.parseInt(IdStr);
               Registros registros = new Registros();
               boolean insertado = registros.insertarProveedor(nom, ubi, id, tel);

               if (insertado)
               {
                    JOptionPane.showMessageDialog(this,
                            "Proveedor registrado exitosamente",
                            "Éxito",
                            JOptionPane.INFORMATION_MESSAGE);
                    CtrlInterfaz.limpia(UProveedor);
                    CtrlInterfaz.limpia(NProveedor);
                    CtrlInterfaz.limpia(IDProveedor);
                    CtrlInterfaz.limpia(TProveedor);
               } else
               {
                    JOptionPane.showMessageDialog(this,
                            "No se pudo registrar al proveedor",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
               }
          } catch (NumberFormatException e)
          {
               JOptionPane.showMessageDialog(this,
                       "El ID debe ser números válidos",
                       "Error",
                       JOptionPane.ERROR_MESSAGE);
          }
     }//GEN-LAST:event_RProductos1ActionPerformed

     private void TProveedorKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_TProveedorKeyTyped
     {//GEN-HEADEREND:event_TProveedorKeyTyped
          Validaciones.validaEntero(evt);
     }//GEN-LAST:event_TProveedorKeyTyped

     private void REmpleadoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_REmpleadoActionPerformed
     {//GEN-HEADEREND:event_REmpleadoActionPerformed
          String nombre = NEmpleado.getText().trim();
          String IdStr = IDEmpleado1.getText().trim();
          String Tel = TEmpleado.getText().trim();

          if (nombre.isEmpty() || IdStr.isEmpty() || Tel.isEmpty())
          {
               JOptionPane.showMessageDialog(this,
                    "Todos los campos son obligatorios",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
               return;
          }

          try
          {

               int id = Integer.parseInt(IdStr);
               int tel = Integer.parseInt(Tel);

               Registros registros = new Registros();
               boolean insertado = registros.insertarEmpleados(nombre, id, tel);

               if (insertado)
               {
                    JOptionPane.showMessageDialog(this,
                         "Empleado registrado exitosamente",
                         "Éxito",
                         JOptionPane.INFORMATION_MESSAGE);
                    CtrlInterfaz.limpia(NEmpleado);
                    CtrlInterfaz.limpia(TEmpleado);
                    CtrlInterfaz.limpia(IDEmpleado1);

               } else
               {
                    JOptionPane.showMessageDialog(this,
                         "No se pudo registrar el producto",
                         "Error",
                         JOptionPane.ERROR_MESSAGE);
               }
          } catch (NumberFormatException e)
          {
               JOptionPane.showMessageDialog(this,
                    "el ID debe ser  un número válido",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
          }
     }//GEN-LAST:event_REmpleadoActionPerformed

     private void CEmpleadoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CEmpleadoActionPerformed
     {//GEN-HEADEREND:event_CEmpleadoActionPerformed
          // TODO add your handling code here:
     }//GEN-LAST:event_CEmpleadoActionPerformed

     private void TEmpleadoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_TEmpleadoKeyTyped
     {//GEN-HEADEREND:event_TEmpleadoKeyTyped
          // TODO add your handling code here:
     }//GEN-LAST:event_TEmpleadoKeyTyped

     private void IDEmpleado1KeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_IDEmpleado1KeyTyped
     {//GEN-HEADEREND:event_IDEmpleado1KeyTyped
          // TODO add your handling code here:
     }//GEN-LAST:event_IDEmpleado1KeyTyped

     private void NEmpleadoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_NEmpleadoKeyTyped
     {//GEN-HEADEREND:event_NEmpleadoKeyTyped
          // TODO add your handling code here:
     }//GEN-LAST:event_NEmpleadoKeyTyped

     /**
      * @param args the command line arguments
      */
     public static void main(String args[])
     {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try
          {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
               {
                    if ("Nimbus".equals(info.getName()))
                    {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex)
          {
               java.util.logging.Logger.getLogger(PrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex)
          {
               java.util.logging.Logger.getLogger(PrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex)
          {
               java.util.logging.Logger.getLogger(PrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex)
          {
               java.util.logging.Logger.getLogger(PrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>
          //</editor-fold>
          //</editor-fold>
          //</editor-fold>
          //</editor-fold>
          //</editor-fold>
          //</editor-fold>
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable()
          {
               public void run()
               {
                    new PrincipalAdministrador().setVisible(true);
               }
          });
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton CEmpleado;
     private javax.swing.JButton CProductos;
     private javax.swing.JButton CProductos1;
     private javax.swing.JButton CProveedores;
     private javax.swing.JButton CargarProductos;
     private javax.swing.JButton CargarProductos1;
     private javax.swing.JButton CargarProductos2;
     private javax.swing.JButton CargarProductos3;
     private javax.swing.JButton CargarProductos4;
     private javax.swing.JButton CargarProductos5;
     private javax.swing.JButton ECliente;
     private javax.swing.JButton EProducto;
     private javax.swing.JPanel Empleados;
     private javax.swing.JButton EmpleadosBtn;
     private javax.swing.JPanel Fondo;
     private javax.swing.JTextField IDEmpleado1;
     private javax.swing.JTextField IDProducto;
     private javax.swing.JTextField IDProveedor;
     private javax.swing.JButton MCliente;
     private javax.swing.JButton MProducto1;
     private javax.swing.JTextField NEmpleado;
     private javax.swing.JTextField NProducto;
     private javax.swing.JTextField NProveedor;
     private javax.swing.JPanel Opciones;
     private javax.swing.JTextField PProducto;
     private javax.swing.JPanel Principal;
     private javax.swing.JPanel Productos;
     private javax.swing.JButton ProductosBtn;
     private javax.swing.JPanel Proveedores;
     private javax.swing.JButton ProveedoresBtn;
     private javax.swing.JButton REmpleado;
     private javax.swing.JButton RProductos;
     private javax.swing.JButton RProductos1;
     private javax.swing.JButton RProveedores;
     private javax.swing.JTable TClientes;
     private javax.swing.JTable TClientes1;
     private javax.swing.JTextField TEmpleado;
     private javax.swing.JTable TProductos;
     private javax.swing.JTextField TProveedor;
     private javax.swing.JTable TProveedores;
     private javax.swing.JPanel TablaClientes;
     private javax.swing.JPanel TablaEmpleados;
     private javax.swing.JPanel TablaProductos;
     private javax.swing.JPanel TablaProveedores;
     private javax.swing.JPanel TablaVentas;
     private javax.swing.JPanel Tablas;
     private javax.swing.JTextField UProveedor;
     private javax.swing.JPanel Ventas;
     private javax.swing.JButton VentasBtn;
     private javax.swing.JComboBox<String> jComboBox1;
     private javax.swing.JLabel jLabel10;
     private javax.swing.JLabel jLabel11;
     private javax.swing.JLabel jLabel12;
     private javax.swing.JLabel jLabel13;
     private javax.swing.JLabel jLabel14;
     private javax.swing.JLabel jLabel15;
     private javax.swing.JLabel jLabel16;
     private javax.swing.JLabel jLabel17;
     private javax.swing.JLabel jLabel18;
     private javax.swing.JLabel jLabel19;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel20;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JLabel jLabel8;
     private javax.swing.JLabel jLabel9;
     private javax.swing.JScrollBar jScrollBar1;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JScrollPane jScrollPane2;
     private javax.swing.JScrollPane jScrollPane3;
     private javax.swing.JScrollPane jScrollPane4;
     private javax.swing.JScrollPane jScrollPane5;
     private javax.swing.JTable jTable1;
     // End of variables declaration//GEN-END:variables
}
